### ISSUE TITLE
Question about compatibility.

### ISSUE THREAD

**Issue by fernando-inf** [jesusvallejo/Midi2Vol-Linux#3]
Hi, I need to control the input and output (volume) audio in ALSA  (GNU/Linux) with my MIDI Controller. But apparently its code is intended exclusively for Nano. ¿I`m right?. Thanks.

P.D: Excuse my ignorance, but what is Nano? I do not know that device.

**Comment by jesusvallejo** [comment]
This device https://www.keebwerk.com/nano-slider/ , anyhow with very little changes should work. 

1. Connection detection line 122, allows hot plug midi and handles notifications of connection and disconnection . As your device has another name(check dmesg) just chage the string checking in 125.

2.Nano slider reports via midi a value from 0 - 127, hence the volume calculation to translate it to 0 -100
   ````volume = math.floor((volumeRaw/3)*2.38)````. 
    Check the values reported by the midi device and change accordingly.

Finally the pulse part of it is far more powerfull, but alsa works.

**Comment by fernando-inf** [comment]
Thanks for the prompt response. I will try to take a good look at your code in the next few days.
